version: '3.8'

services:
  mysql:
    image: mysql:8.2
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: urubu100
      MYSQL_DATABASE: allset
    ports:
      - "3306:3306"
    volumes:
      - ./allset_atualizado.sql:/docker-entrypoint-initdb.d/allset_atualizado.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data: 



